### ISSUE TITLE
ReturnedData.as_dataframe() raising IndexError while specifying expand=True

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Python-Client#55] opened 2020-11-02 13:19 UTC
Issue observed on v.0.7 while executing the following code:

```python
from viresclient import SwarmRequest

request = SwarmRequest()
request.set_collection('SW_OPER_AUX_OBSM2_')
request.set_products(measurements=['F', 'B_NEC', 'IAGA_code', 'Quality'])
df = request.get_between('2016-10-01', '2016-10-02').as_dataframe(expand=True)
```

The following exception is raised:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-48d44dc9f7d0> in <module>
      4 request.set_collection('SW_OPER_AUX_OBSM2_')
      5 request.set_products(measurements=request.available_measurements('SW_OPER_AUX_OBSM2_'))
----> 6 df = request.get_between('2016-10-01', '2016-10-02').as_dataframe(expand=True)

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in as_dataframe(self, expand)
    565         """
    566         return pandas.concat(
--> 567             [d.as_dataframe(expand=expand) for d in self.contents])
    568 
    569     def as_xarray(self):

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in <listcomp>(.0)
    565         """
    566         return pandas.concat(
--> 567             [d.as_dataframe(expand=expand) for d in self.contents])
    568 
    569     def as_xarray(self):

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in as_dataframe(self, expand)
    419         elif self.filetype == 'cdf':
    420             with FileReader(self._file) as f:
--> 421                 df = f.as_pandas_dataframe(expand=expand)
    422         return df
    423 

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in as_pandas_dataframe(self, expand)
    190             if len(vector_data.shape) > 2:
    191                 raise NotImplementedError("{}".format(column))
--> 192             if vector_data.shape[1] != len(suffixes):
    193                 raise NotImplementedError("{}".format(column))
    194             for i, suffix in enumerate(suffixes):

IndexError: tuple index out of range
```

Removing `Quality` from the list of requested measurements, the exception is not raised anymore:

```python
from viresclient import SwarmRequest

request = SwarmRequest()
request.set_collection('SW_OPER_AUX_OBSM2_')
request.set_products(measurements=['F', 'B_NEC', 'IAGA_code'])
df = request.get_between('2016-10-01', '2016-10-02').as_dataframe(expand=True)
```

**Comment by smithara** [comment] 2020-11-02 13:54
Duplicate of https://github.com/ESA-VirES/VirES-Python-Client/issues/54

It's fixed in 0.7.1 but I haven't made the release - you can get it from
`pip install git+https://github.com/ESA-VirES/VirES-Python-Client.git@staging`

Thanks for the reminder on this! It had slipped my mind

**Closed by smithara** 2020-11-02 13:54 UTC

**Comment by lmar76** [comment] 2020-11-02 14:45
Thank you Ashley. Could you please plan the release of the v0.7.1 and update also the VRE? Thank you!

**Comment by pacesm** [comment] 2020-11-02 15:52
I will take care of the VRE update. Just ping me when the release is ready.

**Comment by lmar76** [comment] 2021-01-25 11:12
I think it's ready (see: https://pypi.org/project/viresclient/ )

**Comment by smithara** [comment] 2021-01-25 12:25
Yes sorry I forgot to ask to get the VRE image updated. Since it takes some effort to do, a fixed update cycle around the time of the VirES releases might be preferable. Minor issues like this need not trigger an update - would be simpler to just nudge users to use a `!pip install --upgrade viresclient` in their notebooks if they need a more recent fix.
